config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/users/:id", to: "users#show"
  get "/users/:user_id/posts", to: "posts#index", as: 'posts'
  get "/users/posts/new", to: "posts#new", as: "new_post"
  post "/users/:user_id/posts/:id/comment", to: "comments#comment", as: "new_comment" 
  delete "/users/comment/:id", to: "comments#destroy", as: "delete_comment" 
  post "/users/:user_id/posts/:id/like", to: "likes#like", as: "new_like"
  post "users/:user_id/posts", to: "posts#create"
  delete "/posts/:post_id/delete", to: "posts#destroy", as: "delete_post"
  get "users/:user_id/posts/:id", to: "posts#show", as: "user_post"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/views/shared/_comment.html.erb
<div class="comment">
  <div class="comment-user"><%= comment.author.name %></div>
  <div class="comment-text"><%= comment.text %></div>
    <% if can? :destroy, comment %>
    <%= button_to "Delete", delete_comment_path(id: comment.id), method: :delete, data: {
      turbolinks: false,
    } %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msgs| %>
    <% msgs.each do |msg| %>
      <div class="alert alert-<%= type %>">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_post_detail.html.erb
<div class="post">

  <a href="<%= user_post_path(user_id: post_detail.user_id, id: post_detail.id) %>">
    <div class="post-number">Post #<%= post_detail.id %></div>
  </a>

  <div class="post-detail"><%= post_detail.title %></div>
  <div class="post-detail"><%=h truncate(post_detail.text, :length => 80)%></div>
  <div class="likes-comments">Comments: 
    <%= post_detail.comment_counter == nil ? 0 : post_detail.comment_counter %>, Likes: 
    <%= post_detail.like_counter == nil ? 0 : post_detail.like_counter %>
  </div>
  <%if display_comments == true%>
    <% if current_page?(:controller => 'posts', :action => 'index') %>
      <% if post_detail.comments.length > 0 %>
        <%= render partial: "shared/comment", collection: [ post_detail.comments.last ] %>
      <% end %>
    <% else %>
      <%= render partial: "shared/comment", collection: post_detail.comments %>
    <% end %>
  <%end%>
</div>

app/views/shared/_user.html.erb
<div class='user-details-container'>
  <% if current_page?(:controller => :users, :action => :index) %>
  <a href="/users/<%= user.id %>">
  <% end %>
  <div class='user-details'>
    <img src="<%= user.photo %>" alt="User Photo" />
    <div>
      <div><%= user.name %></div>
      <div>Number of posts: <%= user['post_counter'] == nil ? '0' : user['post_counter'] %></div>
    </div>
  </div>
  <% if current_page?(:controller => :users, :action => :index) %>
  </a>
  <% end %>
</div>