config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/users/:id", to: "users#show"
  get "/users/:user_id/posts", to: "posts#index", as: 'posts'
  get "/users/posts/new", to: "posts#new", as: "new_post"
  post "/users/:user_id/posts/:id/comment", to: "comments#comment", as: "new_comment" 
  delete "/users/comment/:id", to: "comments#destroy", as: "delete_comment" 
  post "/users/:user_id/posts/:id/like", to: "likes#like", as: "new_like"
  post "users/:user_id/posts", to: "posts#create"
  delete "/posts/:post_id/delete", to: "posts#destroy", as: "delete_post"
  get "users/:user_id/posts/:id", to: "posts#show", as: "user_post"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  validates_associated :author

  validates :title, presence: true, length: { in: 1..250 }
  validates :text, presence: true, length: { in: 1..250 }
  validates :comment_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :like_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_destroy :decrement_user_post_counter

  after_save :increment_user_post_counter

  def increment_user_post_counter
    author.increment!(:post_counter)
  end

  def decrement_user_post_counter
    author.decrement!(:post_counter) unless author.post_counter.zero?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  include Modules::FormErrorHandler

  def index
    index = params['user_id']
    @user = User.find(index)
    @posts = Post.where(user_id: @user.id).includes(comments: [:author])
  end

  def show
    user_id = params['user_id']
    @user = User.find(user_id)
    post_id = params['id']
    @post = Post.includes(comments: [:author]).find(post_id)
  end

  def new
    post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: post } }
    end
  end

  def add_post_save_error_messages(msgs)
    flash.now[:danger] = []
    msgs.each do |message|
      flash.now[:danger] << message
    end
    flash.now[:danger] << 'Post could not be saved'
  end

  def create
    new_post = Post.new(post_params)
    errors = []
    errors << 'Title Missing From Post' if params[:post][:title] == ''
    errors << 'Text Missing From Post' if params[:post][:text] == ''
    found_errors = validate_form(errors)

    respond_to do |format|
      format.html do
        unless found_errors
          new_post.author = current_user
          if new_post.save
            flash[:success] = ['Post Created Successfully']
            redirect_to posts_url
            return
          end
          add_post_save_error_messages(new_post.errors.full_messages)
        end
        render :new, locals: { post: new_post }, status: 422
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    authorize! :destroy, @post
    @comment = @post.comments
    @comment.each(&:destroy)
    @post.destroy
    flash[:success] = ['Post Deleted Successfully']

    respond_to do |format|
      format.html { redirect_to "/users/#{current_user.id}/posts" }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_comment.html.erb
<section class="new-comment">
  <%= render partial: 'shared/flash'%>
  <%= form_with model: comment, url: new_comment_path, method: :post, html: {class: "comment-form"}, local: true, scope: :comment, data: {turbo: false} do |f| %>
    <div>
      <%= f.text_area :text, placeholder: "Write Comment", size: "30x5" %>
    </div>
    <%= f.submit "Add Comment" %>
  <% end %>
</section>

app/views/posts/_like.html.erb
<section class="new-like">
  <%= form_with model: like, url: new_like_path, method: :post, html: {class: "like-form"}, local: true, scope: :like do |f| %>
    <%= f.submit "Like", class: 'like-btn' %>
  <% end %>
</section>

app/views/posts/index.html.erb
<%= render partial: 'shared/flash'%>
<br>
<%= render partial: 'shared/user', locals: { user: @user } %>
<br>
<section class='posts'>
  <%= render partial: 'shared/post_detail', collection: @posts, locals: { display_comments: true } %>
  <button>Pagination</button>
</section>

app/views/posts/new.html.erb
<section class="new-post">
  <h1>Create Post</h1>
  <%= render partial: 'shared/flash'%>
  <%= form_with model: post, url: posts_path(user_id: current_user.id), method: post, html: {class: "post-form"}, local: true, scope: :post do |f| %>
    <div>
      <%= f.text_field :title, placeholder: "Post Title" %>
    </div>
    <div>
      <%= f.text_area :text, placeholder: "Place Text", size: "30x5" %>
    </div>
    <%= f.submit "Add Post" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<section class="complete-post">
  <div class="post-head">
    <div>Post #<%= @post.id %> <%= @user.name %></div>
    <div>Comments: 
      <%= @post.comment_counter.nil? ? 0 : @post.comment_counter%>
      , Likes: 
      <%= @post.like_counter.nil? ? 0 : @post.like_counter %></div>
  </div>
  <div class="post-body"><%= @post.text %></div>
  <br>
  <%= render partial: "like", locals: { like: Like.new } %>
  <% if can? :destroy, @post %>
    <%= button_to "Delete", delete_post_path(post_id: @post.id), method: :delete, data: {
      turbolinks: false,
    } %>
  <% end %>
  <br>
  <div class="comments">
    <h3>Comments:</h3>
    <%= render partial: "comment", locals: { comment: Comment.new }%>
    <br>
    <%= render partial: "shared/comment", collection: @post.comments %>
  </div>
</section>